# Generated by Django 3.0.8 on 2020-07-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itens',
            new_name='Produtos',
        ),
    ]
